name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '41 17 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
          tar xzvf trivy_0.20.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          rm trivy_0.20.0_Linux-64bit.tar.gz
      - name: Install trivy-combine
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy-combine_0.20.0_Linux-64bit.tar.gz
          tar xzvf trivy-combine_0.20.0_Linux-64bit.tar.gz
          sudo mv trivy-combine /usr/local/bin/
          rm trivy-combine_0.20.0_Linux-64bit.tar.gz

      - name: Build and scan multiple Dockerfiles
        run: |
          dockerfiles=("Dockerfile" "Dockerfile_desktop")  # List your Dockerfile names here

          for file in "${dockerfiles[@]}"; do
            docker build -t "docker.io/my-organization/my-app:${{ github.sha }}-$file" -f $file .
            trivy image -f json -o "trivy-results-$file.json" "docker.io/my-organization/my-app:${{ github.sha }}-$file"
          done

      - name: Combine Trivy scan results
        run: |
          trivy-combine -o trivy-results-combined.json trivy-results-*.json

      - name: Upload combined Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-combined.json'
